apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapps
  template:
    metadata:
      labels:
        app: testapps
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ["/bin/sh", "-c", "while true; do echo Test! >> /output/test.txt; sleep 5; done"]
          volumeMounts:
            - name: test-volume
              mountPath: /output
        - name: multitool
          image: wbitt/network-multitool:latest
          env:
            - name: HTTP_PORT
              value: "1180"
            - name: HTTPS_PORT
              value: "11443"
          ports:
            - containerPort: 1180
              name: http-port
            - containerPort: 11443
              name: https-port
          volumeMounts:
            - name: test-volume
              mountPath: /input
      volumes:
        - name: test-volume
          emptyDir: {}