{
 "title": "Netology",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mem util",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job=\"nodeexporter\"}",
     "legendFormat": "RAM"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{job=\"nodeexporter\",mountpoint=\"/\"}",
     "legendFormat": "Disk free"
    }
   ]
  },
  { "title": "CPU Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU LA",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (instance)(rate(node_load1{}[$__rate_interval]))",
     "legendFormat": "LA1"
    },
    {
     "expr": "avg by (instance)(rate(node_load5{}[$__rate_interval]))",
     "legendFormat": "LA5"
    },
    {
     "expr": "avg by (instance)(rate(node_load15{}[$__rate_interval]))",
     "legendFormat": "LA15"
    }
   ]
  },
  {
   "title": "CPU Util",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\",job=\"nodeexporter\"}[1m])) * 100)",
     "legendFormat": "утилизация CPU для nodeexporter"
    }
   ]
  }
 ]
}