---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-2
  labels:
    app: dep-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dep-2
  template:
    metadata:
      labels:
        app: dep-2
    spec:
      containers:
        - name: nginx
          image: nginx
      initContainers:
        - name: busybox
          image: busybox
          command: ['sh', '-c', 'until nslookup service-2.default.svc.cluster.local; do echo Waiting for service-2!; sleep 5; done;']
