---
apiVersion: v1
kind: Service
metadata:
  name: srv-1
spec:
  selector:
    app: dep-1
  ports:
    - name: nginx-http
      port: 80
      targetPort: 80
    - name: multitool-http
      port: 1180
      targetPort: 1180
    - name: multitool-https
      port: 11443
      targetPort: 11443