---
- name: Get Nexus installed
  hosts: nexus
  pre_tasks:
    - name: Create Nexus group
      become: true
      group:
        name: nexus
        state: present
    - name: Create Nexus user
      become: true
      user:
        name: nexus
    - name: Install JDK
      become: true
      package:
        name: [java-1.8.0-openjdk, java-1.8.0-openjdk-devel]
        state: present
  tasks:
    - name: Create Nexus directories
      become: true
      file:
        group: nexus
        owner: nexus
        path: "{{ item }}"
        state: directory
      with_items:
        - "/home/nexus/log"
        - "/home/nexus/sonatype-work/nexus3"
        - "/home/nexus/sonatype-work/nexus3/etc"
        - "/home/nexus/pkg"
        - "/home/nexus/tmp"

    - name: Download Nexus
      become: true
      become_user: nexus
      get_url:
        dest: "/home/nexus/pkg/nexus-3.14.0-04.tar.gz"
        url: "https://download.sonatype.com/nexus/3/nexus-3.14.0-04-unix.tar.gz"
        validate_certs: false

    - name: Unpack Nexus
      become: true
      become_user: nexus
      unarchive:
        copy: no
        creates: "/home/nexus/pkg/nexus-3.14.0-04"
        dest: "/home/nexus/pkg"
        src: "/home/nexus/pkg/nexus-3.14.0-04.tar.gz"

    - name: Link to Nexus Directory
      become: true
      become_user: nexus
      file:
        dest: "/home/nexus/nexus"
        src: "/home/nexus/pkg/nexus-3.14.0-04"
        state: link

    - name: Add NEXUS_HOME for Nexus user
      become: true
      become_user: nexus
      lineinfile:
        create: yes
        dest: "/home/nexus/.bashrc"
        insertafter: EOF
        line: "export NEXUS_HOME=/home/nexus/nexus}"

    - name: Add run_as_user to Nexus.rc
      become: true
      become_user: nexus
      lineinfile:
        create: yes
        dest: "/home/nexus/nexus/bin/nexus.rc"
        insertafter: EOF
        line: "run_as_user=\"nexus\""
        regexp: "^run_as_user"

    - name: Raise nofile limit for Nexus user
      become: true
      pam_limits:
        domain: "nexus"
        limit_type: "-"
        limit_item: nofile
        value: "65536"

    - name: Create Nexus service for SystemD
      become: true
      template:
        dest: /lib/systemd/system/nexus.service
        mode: 0644
        src: nexus.systemd.j2

    - name: Ensure Nexus service is enabled for SystemD
      become: true
      systemd:
        daemon_reload: yes
        enabled: yes
        name: nexus
      when:
        - true

    - name: Create Nexus vmoptions
      become: true
      become_user: "nexus"
      template:
        dest: "/home/nexus/nexus/bin/nexus.vmoptions"
        src: nexus.vmoptions.j2
      register: nexus_config_changed

    - name: Create Nexus properties
      become: true
      become_user: "nexus"
      template:
        dest: "/home/nexus/sonatype-work/nexus3/etc/nexus.properties"
        src: nexus.properties.j2
      register: nexus_config_changed

    - name: Lower Nexus disk space threshold
      become: true
      become_user: "nexus"
      lineinfile:
        backrefs: yes
        dest: "/home/nexus/nexus/etc/karaf/system.properties"
        insertafter: EOF
        line: "storage.diskCache.diskFreeSpaceLimit=~}"
        regexp: ^storage\.diskCache\.diskFreeSpaceLimit
      when: nexus_configuration_disk_free_space_limit is not none
      register: nexus_config_changed

    - name: Start Nexus service if enabled
      become: true
      service:
        enabled: yes
        name: nexus
        state: started
      when:
        - true
        - not nexus_config_changed.changed
      tags:
        - skip_ansible_lint

    - name: Ensure Nexus service is restarted
      become: true
      service:
        name: nexus
        state: restarted
      when:
        - true
        - nexus_config_changed.changed
      tags:
        - skip_ansible_lint

    - name: Wait for Nexus port if started
      wait_for:
        port: "8081"
        state: started
        timeout: "600"
      when:
        - true