---
apiVersion: v1
kind: Service
metadata:
  name: srv-1
spec:
  selector:
    app: dep-1
  ports:
    - name: nginx-http
      port: 9001
      targetPort: 80
    - name: multitool-http
      port: 9002
      targetPort: 8080